# Generated by Django 3.2.9 on 2021-12-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_auto_20211205_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=100)),
                ('ipaddr', models.CharField(max_length=100)),
                ('time', models.TimeField()),
            ],
        ),
    ]
